### ISSUE TITLE
Error thrown attached to global handler 

### ISSUE THREAD

**Issue by askho** [PSPDFKit/Cordova-iOS#15]
Hi It looks like an error is being thrown when attached to the global exception handler: 

Adding the below code inside of index.js  
`window.onerror = function(error) {
          console.log(error);
        }`

will log out this error:
> SyntaxError: Unexpected token ','. Expected ':' after property name.

When you switch between pdf pages, and zoom in.

**Comment by Compulsed** [comment]
I am encountering the same issue, though I do not need to add that additional code to see the error.

**Comment by juliangrosshauser** [comment]
We didn't quote some JSON values, that's why those errors showed up.

Thanks for opening this issue!
