### ISSUE TITLE
Opening PDFs from cordova.file.dataDirectory

### ISSUE THREAD

**Issue by jadsalhani-novium** [PSPDFKit/Cordova-iOS#18]
Hello

Been using your reader during my Demo period, really like it. I'm just facing one issue at the moment;

I download PDFs online through Cordova FileTransfer plugin, and then want to open them in the reader. Problem is, the reader isn't recognizing the file:/// path that points to the file, even though in cordova terms it is absolute. And even when I try using ~, the paths used are the same, but the file still doesn't open

Any help would be appreciated!

**Comment by jadsalhani-novium** [comment]
Made it work by passing the filename after adding `~/Library/NoCloud` at the beginning. It should have a way to support direct NativeURLs though, would be much easier to directly pass files

Thanks for the support and great plugin!

**Comment by steipete** [comment]
Thanks! We'll add this as an enhancement in one of the next updates here;

**Comment by steviki** [comment]
Hi,

We just updated the plugin to add support for this kind of paths.

Please update to the latest plugin and let us know if it works.

(If not, please reopen this ticket and add the exact document path you pass to `PSPDFKitPlugin.present(..)`)

Thanks!
