### ISSUE TITLE
Disable Annotations & Document Editor

### ISSUE THREAD

**Issue by phillipplum** [PSPDFKit/Cordova-iOS#19]
I would like to disable the annotations and the document editor.

Is this posible?

**Comment by steipete** [comment]
Sure! The wrapper is open source. You can customize how PSPDFConfiguration is called to suite your needs.

Documentation is here:
https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html

The document editor is automatically disabled if you do not license it, and so are annotations. So this will all be done automatically if you add a license key that does not include these components.
