### ISSUE TITLE
Thread warning when loading a PDF

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#23]
THREAD WARNING: ['PSPDFKitPlugin'] took '453.686279' ms. Plugin should use a background thread.

This warning shows everytime I load a PDF.

Using version 6.5.1 of the framework.
Cordova: 6.5.0
Ionic 2:  2.3.0
Ios-Cordova -platform: 4.3.0

I have experienced this issue in older versions of the plugin.

**Comment by steipete** [comment]
This is an architectural issue that isn't easy to fix - we track that internally on the PSPDFKit repo and will improve that over the course of 2018. Thanks for filing!
