### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by CinnamonRage** [PSPDFKit/Cordova-iOS#25]
Hi, can you explain how this works with Ionic 2? A wee sample would be really useful.

I tried adding 
```typescript 
declare var cordova: any;
``` 
to the file and then called this below:

``` typescript
let fileNative = new File();
this.platform.ready().then(() => {
  cordova.PSPDFKitPlugin.setLicenseKey('KEY');
  cordova.PSPDFKitPlugin.present(`${fileNative.dataDirectory}/${file.name}`, {
    pageTransition: 'curl',
    pageMode: 'double',
    backgroundColor: 'red'
  });
});
```

Anyone can help?

Thanks!

**Comment by twinj** [comment]
In your typings declare the kit like this.

`declare var PSPDFKitPlugin: any;`

Use the new @ionic-native/file plugin as per the docs.
I created a menu item which calls this function.

`/**
   * Open PSPDFKit Demo PDF.
   */
  public openPSPDFKitDemo() {
    // Show PDF with curl transition and white background
    // this.file represents the native file plugin injected using Angular 2 and Ionic-native.
    // this is the location I save the asset to you could open it from web assets directly
   // present(this.file.applicationDirectory + 'www/' + location
    PSPDFKitPlugin.present(this.file.dataDirectory + 'demo/' + this.psPDFKitDemo, {
      pageTransition: 'curl',
      pageMode: 'double',
      backgroundColor: 'red',
    });
  }`

In your app component onInit

`// set your license key here
      PSPDFKitPlugin.setLicenseKey(...);
`

At this stage I am bundling the pdf as a web asset so I have to copy the file to the no cloud library so that annotations can be saved.

`this.file.checkFile(this.file.dataDirectory, 'demo/' + this.psPDFKitDemo)
        .then(fileIs => {
            this.logger.info('PSPDFKit Demo already saved.', fileIs);
          },
          fileIsError => {
            this.logger.error('PSPDFKit file error', fileIsError);
            const NOT_FOUND_ERR = 1;

            if (fileIsError.code === NOT_FOUND_ERR) {
              // copy file to app
              this.file.checkDir(this.file.dataDirectory, 'demo')
                .then(dirIs => {
                  if (dirIs) {
                    this.logger.info('PSPDFKit demo dir exists.', dirIs);
                    this.copyFile();
                  }
                })
                .catch(dirIsError => {
                  this.logger.error('PSPDFKit dir error', dirIsError);
                  this.file.createDir(this.file.dataDirectory, 'demo', false)
                    .then(() => {
                    this.copyFile();
                  });
                });
            }
          }
        );`

**Comment by twinj** [comment]
Are you using WKWebKit engine by chance?

**Comment by CinnamonRage** [comment]
I got it working, thank you. Works well, thank you. The only issue is that when it dismisses, it returns me to a white screen. Sometimes, and I mean very rarely, it will return to my view but only rarely.

**Comment by twinj** [comment]
Interesting, are you opening from a web asset or the file system? Web assets are read only, opening from there can cause issues. I suspect that maybe the cause of the screen problem.

**Comment by CinnamonRage** [comment]
I'm opening it from file system. It opens the file fine, the issue is when closing - when it closes, the view that launched the PDF viewer is just a scrollable white screen.

I opened another issue to try and keep this one cleaner as you had answered my previous question :-) 

https://github.com/PSPDFKit/Cordova-iOS/issues/29
