### ISSUE TITLE
How to add external/remote pdf file path in the plugin.

### ISSUE THREAD

**Issue by midhunkrishnakv** [PSPDFKit/Cordova-iOS#35]
Hi ,
Is there any way to open pdfs located in a remote server by giving the remote path.
I am now able to open documents stored locally. Please help and let me know if its possible. I tried giving the remote path of a pdf file but it says "Unable to display  document".

**Comment by steipete** [comment]
The PDF needs to be fully downloaded and on disk before it can be displayed. Remote locations will not work.
