### ISSUE TITLE
Setting shouldAskForAnnotationUsername false still asks for name on first run

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#36]
When setting this in either _setOptions_ or _present_ function as false, pspdfkit still asks for the username.

**Comment by steviki** [comment]
This property (`shouldAskForAnnotationUsername`) is currently not exposed in the Cordova bindings, and therefore is ignored. We will add this functionality.

Thanks for the request.

**Comment by twinj** [comment]
Ahh that explains it then. 🤓 Thanks.

**Comment by steviki** [comment]
`shouldAskForAnnotationUsername` has been exposed in https://github.com/PSPDFKit/Cordova-iOS/commit/2bdb4243288b9e0a2bf122e3b941208d5daf3f43.

This can now be used via

```
PSPDFKitPlugin.present('pdf/PSPDFKit 6 QuickStart Guide.pdf', {
    shouldAskForAnnotationUsername: false
});
```
