### ISSUE TITLE
Custom Save Button implemetation

### ISSUE THREAD

**Issue by firozcitrus** [PSPDFKit/Cordova-iOS#37]
Is it possible to create custom save / manual save button,so that we can save every changes we make and also after  success call back we should be able to upload document to our server.

**Comment by midhunkrishnakv** [comment]
Hi, 
Please let us know on this issue as soon as possible, as we need to confirm about the pspdfkit subscription based on the factor, if the library could solve our project requirement as mentioned in the above issues.
We are waiting for your response.

**Comment by radazzouz** [comment]
Hi @firozcitrus and @midhunkrishnakv , 

You can create a custom save button which calls `- [PSPDFDocument save:]` to save manually: https://pspdfkit.com/guides/ios/current/annotations/when-will-pspdfkit-save-annotations/

**Comment by steviki** [comment]
Note that this functionality is also exposed in the Cordova plugin as `saveAnnotations:` here: https://github.com/PSPDFKit/Cordova-iOS/blob/master/PSPDFKitPlugin/PSPDFKitPlugin.m#L1096

Pleas let us know if this works for you or if you have any questions.

**Comment by firozcitrus** [comment]
hi @steviki ,
       We want a final Submit Button.If a user open a document and add some stike,or text ect..,after that user remember opened document is wrong. so close and open new document . so " saveAnnotation" option is not much process to upload that document to server (in our case). Any options in pspdf cordova-ios plugin.

**Comment by steviki** [comment]
@firozcitrus:
Uploading a document to a server is not part of the PSPDFKit logic, but should be part of your app logic. `saveAnnotations:` should be the exact entry point you are looking for:
- The user makes some annotations on a document.
- Your custom Submit button is tapped, which calls `saveAnnotations:` to save any changes into the PDF.
- You upload the document to your server.

**Comment by midhunkrishnakv** [comment]
@steviki ,
              We Know the upload document to server is our part , But in your side not provide a final submit button. Each 'saveAnnotation:' trigger call a  upload document to server function is a bad practices .  in your documentation a " Custom toolbar button format option [https://github.com/PSPDFKit/Cordova-iOS#custom-toolbar-button-format]". But can't identify how to implement .
Our coding like this,
`PSPDFKitPlugin.present( fileName ,{pageTransition: 'curl', backgroundColor: 'white'});
PSPDFKitPlugin.saveAnnotations(function(success){
  console.log(success);
});`
 But the saveAnnotation  callback is not working.

**Comment by radazzouz** [comment]
> Each 'saveAnnotation:' trigger call a upload document to server function is a bad practices.

`saveAnnotation` is not (and should not be) tied to the uploading the upload logic. It is up to you to decide when (and if) to upload in your custom Submit button function. For example, your logic will upload to the server only if your custom Save button is tapped, but not every time an annotation is saved.

> But the saveAnnotation callback is not working.

It is not working because it's an error callback. In other words, the call back is only called if an error occurred while saving the annotation, otherwise the callback parameter will be null (see the README).

<img width="912" alt="pspdfkit_cordova-ios__this_is_the_official_plugin_to_use_pspdfkit_with_apache_cordova_" src="https://user-images.githubusercontent.com/7443038/27913867-702a07d4-622f-11e7-9b78-91c7f3a1f13d.png">

**Comment by radazzouz** [comment]
Oh and BTW, since we're discussing uploading your PDF document to a server.

Make sure you take a look at our upcoming [PSPDFKit Instant](https://pspdfkit.com/instant/) syncing solution.

I’m going ahead and close this issue, but please feel free to follow up in here.

**Comment by firozcitrus** [comment]
We were checking the Custom toolbar button format to save the document to our server as you suggested. But we didn't get an idea of how we can implement this. For example, where should we implement the below code. 

`{title: 'Hello', action: function() {
    //do something
});`

We have tried the below option  also, and here the 'items' is an array but in the above code it is an object. So we are getting an error here.

`setLeftBarButtonItems(items);
setRightBarButtonItems(items);`

Can you please advise the needful asap because we are stuck at this point and our client needs it as an emergency and we need to provide them a date.

**Comment by steviki** [comment]
There was a small syntax error in the README for the button, which has been corrected now.

Please use the following (or an adaption of the) code to show a custom save button.

```js
var saveButton = {title: 'Save', action: function() {
    PSPDFKitPlugin.saveAnnotations( function(error) {
        if (error == null) {
            alert('Annotations saved!');
        } else {
            alert('Error when saving annotations:' + error);
        }
    });
}};
PSPDFKitPlugin.setRightBarButtonItems([saveButton])
```
