### ISSUE TITLE
pageGrabberEnabled configuration settings is not exposed

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#39]
Settings this to true in setOptions has no affect.

**Comment by radazzouz** [comment]
`pageGrabberEnabled ` has been exposed in https://github.com/PSPDFKit/Cordova-iOS/commit/e1b58f54c1f1ec60f04f0aa5268121cd04962012.

It can now be used via

```
PSPDFKitPlugin.present('pdf/PSPDFKit 6 QuickStart Guide.pdf', {
    pageGrabberEnabled: true
});
```
