### ISSUE TITLE
Scroll direction setting does not apply

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#43]
Using the present method. I am not using curl.

**Comment by steipete** [comment]
HI! Can you paste the code that you used? Here's the relevant section in the Cordova translation table:

```
 @{@"scrollPerPage": @(PSPDFPageTransitionScrollPerPage),
    @"scrollContinuous": @(PSPDFPageTransitionScrollContinuous),
    @"curl": @(PSPDFPageTransitionCurl)},
```
https://github.com/PSPDFKit/Cordova-iOS/blob/master/PSPDFKitPlugin/PSPDFKitPlugin.m#L547-L549

**Comment by twinj** [comment]
this.psPDFKit.present(this.download.path, {
      title: this.download.document.title,
      defaultAnnotationUsername: this.storageService.claims.name,
      pageGrabberEnabled: this.storageService.settings.pageGrabberEnabled,
      pageMode: this.storageService.settings.pageMode,
      pageTransition: this.storageService.settings.pageTransition,
      viewMode: this.storageService.settings.viewMode,
      scrollDirection: this.storageService.settings.scrollDirection,
    });

I am using scrollDirection which is either ''vertical' or 'horizontal'

**Comment by steviki** [comment]
Hi there,

Changing the scroll direction is not supported when using the curl page transition. The direction will always be set to horizontal in that case.

We will improve our documentation on that front, to make this more clear.

**Comment by twinj** [comment]
Not using curl.

Sent from my iPhone

On 20 Jul 2017, at 6:19 pm, Stefan Kieleithner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

Changing the scroll direction is not supported when using the curl page transition. The direction will always be set to horizontal in that case.

We will improve our documentation on that front, to make this more clear.

**Comment by steviki** [comment]
Ah, I'm sorry, I misread that.

Will take a further look.

**Comment by twinj** [comment]
Thanks heaps. You guys always respond really quickly. It's very much appreciated!!!!

Sent from my iPhone

On 20 Jul 2017, at 6:23 pm, Stefan Kieleithner <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #43<https://github.com/PSPDFKit/Cordova-iOS/issues/43>.

**Comment by steviki** [comment]
Our apologies, there was a mismatch in the scroll direction mapping, where it used the wrong strings to map to the scroll direction enum.

This now works correctly by using either "vertical" or "horizontal".

Thanks for bringing this to our attention!
