### ISSUE TITLE
Error: Cannot find plugin.xml for plugin "Cordova-iOS". Please try adding it again.

### ISSUE THREAD

**Issue by TheMrugraj** [PSPDFKit/Cordova-iOS#55]
I am getting Error 
`(node:21362) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cannot find plugin.xml for plugin "Cordova-iOS". Please try adding it again.`
`(node:21362) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

When I tried to add plugin using the command:
`ionic cordova plugin add https://github.com/PSPDFKit/Cordova-iOS.git`

**Comment by radazzouz** [comment]
@TheMrugraj closing this issue as a duplicate. We already followed up on the internal [support request](https://support.pspdfkit.com/hc/en-us/requests/new).

BTW, this doesn't look like an issue with the Cordova/Ionic plugin. I created a new Ionic project using the instructions from the [readme](https://github.com/PSPDFKit/Cordova-iOS#ionic), and I didn't get this error when I invoked `ionic cordova plugin add https://github.com/PSPDFKit/Cordova-iOS.git`
