### ISSUE TITLE
using outdated event handlers

### ISSUE THREAD

**Issue by bocodigital** [PSPDFKit/Cordova-iOS#58]
still using```[PSPDFViewControllerDelegate pdfViewController: didShowPageView:]``` instead of 
```[PSPDFViewControllerDelegate pdfViewController: willBeginDisplayingPageView: forPageAtIndex:]``` just to name one. Look like there are still several legacy event handlers in here.

**Comment by radazzouz** [comment]
Thanks for reporting, @bocodigital!
