### ISSUE TITLE
Setting renderAnnotationTypes on the present function options appears to have no effect

### ISSUE THREAD

**Issue by greggarson** [PSPDFKit/Cordova-iOS#62]
Hi there,

We're currently using the Cordova plugin with PSPDFKit for iOS 7.5.0 and are attempting to configure the annotations bar thusly:

```
PSPDFKitPlugin.present(data.documentURL, {
      rightBarButtonItems: ['annotation', 'search', 'thumbnails'],
      renderAnnotationTypes: ['Highlight'],
      pageMode: 'single',
      title: '',
      thumbnailBarMode: 'none',
      HUDViewMode: 'automatic'
    });
```

this doesn't appear to have any noticeable effect on which buttons show up and which don't.  Am I using the `renderAnnotationTypes` option incorrectly?

Thanks.

**Comment by radazzouz** [comment]
> this doesn't appear to have any noticeable effect on which buttons show up and which don't. Am I using the renderAnnotationTypes option incorrectly?

`renderAnnotationTypes` should be used for annotation types that you want to be rendered. See our [Disable Rendered Annotation Types](https://pspdfkit.com/guides/ios/current/annotations/disable-rendered-annotation-types/) article for more details.

If you're looking into [controlling what types of annotations can be edited/created](https://pspdfkit.com/guides/ios/current/annotations/configuring-editablevisible-annotation-types/#control-what-types-can-be-edited-created) (annotation toolbar buttons, etc.), please use [editableAnnotationTypes](https://pspdfkit.com/api/ios/Classes/PSPDFAnnotationToolbar.html#/c:objc(cs)PSPDFAnnotationToolbar(py)editableAnnotationTypes).

Please also have a look at our [Controlling PDF Document Editing](https://pspdfkit.com/guides/ios/current/features/controlling-pdf-editing/).

I’m going ahead and close this issue for now, but please feel free to follow up in here.

**Comment by greggarson** [comment]
Perfect, exactly what I needed, thanks.
