### ISSUE TITLE
Is it possible to integrate this package via cocoapods?

### ISSUE THREAD

**Issue by KatGr** [PSPDFKit/Cordova-iOS#72]
Can I use cocoapods to integrate PSPDFKit for cordova-ios? I know that there is a manual for ios but does it also work for the cordova-version?

**Comment by radazzouz** [comment]
Hi there,

Our Cordova plugin only supports the manual integration at the moment, but we definitely want to explore adding the option to also integrate with CocoaPods.

It seems that plugins like https://www.npmjs.com/package/cordova-plugin-cocoapod-support would allow the CocoaPods integration.

Leaving this issue open so we can explore this. We always welcome pull request contributions from the community :)

Thank you!

**Comment by KatGr** [comment]
Ho,

using cordova-plugin-cocoapod-support hast worked!

Thank you!
