### ISSUE TITLE
Prefill and PDF-Export - Will there be an implementation?

### ISSUE THREAD

**Issue by KatGr** [PSPDFKit/Cordova-iOS#74]
Hello,

I work at a company already using your websdk for one of our products.
We also integrated a demo-pspdfkit in our cordova-ios application.

Unfortunately we need to be able to export  pdf's and to prefill a pdf-form and it seems none is implemented yet.
Will there be an implementation of those Functions?
Or is it somehow possible to export and prefill and we just didn't find out how to do it?

**Comment by steipete** [comment]
Hi!

Our Cordova wrappers are currently optimized for viewing and annotating/filling forms via UI. We haven't yet added API that would allow this to be done programmatically.

We made all of our wrappers open source, so our partners can extend them as needed. We're also open to accept pull requests and will keep maintaining the additions once merged.

What company do you work for? If you can't disclose this here, you can also send us a support ticket at https://pspdfkit.com/support/request/

**Comment by radazzouz** [comment]
We implemented [form filling](https://github.com/PSPDFKit/Cordova-iOS#forms-api) and [annotations API](https://github.com/PSPDFKit/Cordova-iOS#annotation-api) in #75. Closing this issue.
