### ISSUE TITLE
Mapping Annotation Constants 

### ISSUE THREAD

**Issue by greggarson** [PSPDFKit/Cordova-iOS#78]
Hi there,

I'm trying to make use of editableAnnotationTypes to set specific annotations as available in our PDF Reader.  As discussed in a previous issue the set of available options appears to be represented here: https://pspdfkit.com/api/ios/Other%20Constants.html 

The docs for this plugin state: `editableAnnotationTypes (see online documentation)` so I assume the page referenced above is the one intended.

My question though is, when `editableAnnotationTypes` is not set, a subset of annotations options are provided.  One of the options that falls under 'FreeText' and two of the options from 'Ink' etc.  When specifying those options however you end up with a larger set of tools.  Is there a way to specify only the variants you want?  Rather than the collected Ink and FreeText tool groups?  I'm assuming what I want is to be able to reference these: `PSPDFAnnotationVariantStringInkPen`, `PSPDFAnnotationVariantStringInkHighlighter`, `PSPDFAnnotationVariantStringInkMagic`, `PSPDFAnnotationVariantStringLineArrow`, `PSPDFAnnotationVariantStringFreeTextCallout` in some fashion.

Thanks.

**Comment by aksh1t** [comment]
Hello! For the use case that you mention, I don't think that `editableAnnotationTypes` is the correct API to be looking at. `editableAnnotationTypes` was designed to work with annotation types as a whole (`PSPDFAnnotationString`) and not their variants (`PSPDFAnnotationVariantString`). If you want users to not be able to create new annotations of a specific subtype, you should look into [customizing the annotation toolbar](https://pspdfkit.com/guides/ios/current/customizing-the-interface/customize-the-annotation-toolbar/#toolbar-buttons) - that will allow you to enable/disable specfic variants of an annotation. We also have a [guide](https://pspdfkit.com/guides/ios/current/features/controlling-pdf-editing/) on controlling PDF editing, which goes over several different ways to change annotation modification.

**Comment by aksh1t** [comment]
I am closing this issue, but please do not hesitate to reach out to us in https://support.pspdfkit.com/hc/en-us/requests/new should you have any further questions.
